receivers:
  otlp:
    protocols:
      grpc:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

exporters:
  otlp:
    endpoint: zipkin-all-in-one:4317
    tls:
      insecure: true

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

processors:
  batch:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, otlp]